<?php

/**
* Plugin Name: BT-Active Discussions
* Plugin URI: http://www.blogthority.com/bt-active-discussions/
* Description: BT-Active Discussions is a drop in module to output forums-style active discussions table.
* Author: Pinyo Bhulipongsanon
* Author URI: http://www.blogthority.com/
* Version: 1.2.0
* License: GNU General Public License version 3 (GPLv3) - See http://www.opensource.org/licenses/gpl-3.0.html
*/
 
/*
Copyright (C) 2008 Pinyo Bhulipongsanon

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
*/

// ######################### USER CONFIGURABLE OPTIONS     #########################

$show_credit_link = 1;   // set to 0 to remove credit link
$inc_trackbacks   = 0;   // set to 1 to include trackbacks
$max_topics       = 30;  // the number of posts you want to display
$show_gravatar    = 1;   // 0 = off / 1 = on
$excerpt_length   = 250; // number of characters in excerpt.  set to 0 for no excerpt.

// ######################### DO NOT MODIFY BELOW THIS LINE #########################

load_plugin_textdomain('btad',$path='wp-content/plugins/bt-actve-discussions');
add_action('wp_head', 'btad_header');
add_filter('the_content','btad_callback', 7);

function btad_header() {	
	echo '<!-- Start Of Script Generated By BT-Active Discussions -->'."\n";
	echo '<link rel="stylesheet" href="'.get_option('siteurl').'/wp-content/plugins/bt-actve-discussions/btad.css" type="text/css" media="screen" />'."\n";
	echo '<!-- End Of Script Generated By BT-Active Discussions -->'."\n";
}

// Wrapper function which calls the table.
function btad_callback($content) {
	if (strpos($content,'%%bt-active-discussions%%')!== false) {
		global $wpdb, $inc_trackbacks, $max_topics, $show_credit_link, $excerpt_length, $show_gravatar;

		if ($inc_trackbacks == 0) { $inc_trackbacks_txt = " AND comment_type = ''"; } else { $inc_trackbacks_txt = ""; }
		if ($chk_password == 0) { $chk_password_txt = ""; } else { $chk_password_txt = " post_password = '' AND"; }

		$sql = "SELECT post_title, ID, comment_content, comment_count, comment_author, comment_date, comment_ID, comment_author_email FROM $wpdb->comments AS C JOIN $wpdb->posts AS P ON ( ID = comment_post_ID ) WHERE post_password = '' AND comment_ID = (SELECT MAX( comment_ID ) FROM $wpdb->comments WHERE comment_approved = '1'" . $inc_trackbacks_txt . " AND P.ID = comment_post_ID) ORDER BY comment_ID DESC LIMIT " . $max_topics;

			
		$comments = $wpdb->get_results($sql);

		$output  = "<div id=\"recenttable\"><table cellpadding=\"2\" cellspacing=\"0\">";
		$output .= "\n\t<thead><tr>";
		$output .= "<th scope=\"col\">Posts</th>";
		$output .= "<th scope=\"col\" style=\"min-width:100px;text-align:left\">Last Comment</th>";
		$output .= "</tr></thead>";
		$output .= "\n\t<tbody>";
		$alt = 0;
			
		foreach ($comments as $comment) {
			$output .= "\n\t<tr class=\"row-" . $alt%2 . "\"><td valign=\"top\"><a href=\"" . get_permalink($comment->ID) . "\"><strong>" . $comment->post_title . "</strong></a> (" . $comment->comment_count . " comments)<br /> ";

if ($excerpt_length > 0) { $output .= substr(strip_tags($comment->comment_content),0,$excerpt_length)." [...]"; }
			$output .= "<td valign=\"top\">";

if ($show_gravatar <> 0) { $output .= "<img src=\"http://www.gravatar.com/avatar.php?gravatar_id=" . md5($comment->comment_author_email) . "&amp;rating=PG&amp;size=40\" alt=\"gravatar\" style=\"margin:4px 2px 2px 0\" /><br />"; }
			$output .= "<a href=\"" . get_permalink($comment->ID) . "#comment-" . $comment->comment_ID  . "\">" . $comment->comment_author . " </a><br /><small>" . $comment->comment_date . "</small></td></tr>";
			$alt++;
		}
		$output .= "\n</tbody></table></div>";

		If ($show_credit_link == 1) { $output .= "<p><small>Powered by <a href=\"http://www.blogthority.com/bt-active-discussions/\">Blogthority BT-Active Discussions Plugin</a></small></p>";}

		return str_replace('%%bt-active-discussions%%', $output, $content);
	}
	return $content;
}

?>